### PR TITLE
Enable colored ouput by changing default_cli_executable

### LINKED ISSUE #49: Is it possible to make a logger output colorful like in `mix test`?
``` elixir
defmodule Test do
  use ExUnit.Case
  require Logger

  test "color" do
    Logger.warn "warn"
    Logger.error "error"
  end
end
```

selection_004
selection_005

### PR DESCRIPTION
**Pull request by grantwest**
Fixes #49 thanks to @danielspofford

Explanation here: https://github.com/lpil/mix-test.watch/issues/49#issuecomment-1848837003

### CODE REVIEW

**Comment by grantwest** [comment]
I'll be testing this on various projects and environments, however I mostly work on Mac. Maybe others can test on Windows/Linux?

It is easy to pull in this change, just change your mix.exs deps entry to:
```
{:mix_test_watch, github: "grantwest/mix-test.watch", only: [:dev, :test], runtime: false},
```

@astery and @doughsay maybe you can test since you authored/commented on the issue?

**Review by lpil — COMMENTED** [review]
Thank you! Could you update the changelog also? Thanks

**Comment by grantwest** [comment]
Done

**Review by lpil — APPROVED** [review]
Thank you

**Pull request merged**
