### PR TITLE
Modules for re-running tests with existing VM

### PR DESCRIPTION
**Pull request by lpil**

### CODE REVIEW

**Comment by lpil** [comment]
It seems we can disable these warning messages, there there is no clear API for doing so.

https://github.com/elixir-lang/elixir/blob/master/lib/elixir/src/elixir_module.erl#L408-L418
https://github.com/elixir-lang/elixir/blob/master/lib/elixir/src/elixir_compiler.erl#L8-L13

**Comment by liveforeverx** [comment]
@lpil : Code.compiler_options(ignore_module_conflict: true)

**Comment by lpil** [comment]
Ah! Thank you. I completely failed to find that.

What do you think of the idea of disabling those warnings like this?

**Comment by lpil** [comment]
Code review please @omnibs @meadsteve @jonnyarnold

**Comment by omnibs** [comment]
Just tested it. 

Tests suite from the branch ran fine on Windows. :+1: 

Added as local dep on a simple project and ran `mix test.watch`, it ran the tests. :+1: 

Changed the test file, it re-ran the tests detecting my changes. :+1: 

Changed it again, nothing happened. :cry:

Lemme take a quick look and see if I can find anything.

**Comment by lpil** [comment]
AH yes, the actual test running bit is not included in this PR. I just want people to look over these modules as it got a bit hairy while writing them.

**Comment by omnibs** [comment]
Oh ok

**Comment by omnibs** [comment]
I guess we could document why we have to reenable tasks, unload files, ignore module conflicts, and have `:elixir_config.put(:at_exit, [])`. These things might change in future versions of Elixir and the reason why they were there will become more relevant.

You're pushing a lot of levers to make things work, I'm not sure this kind of code can be beautiful, but it can be easier to understand.

**Pull request merged**
