### PR TITLE
reuse the existing vm for running tests

### PR DESCRIPTION
**Pull request by liveforeverx**
Instead of starting always new vm(:os.cmd), this should take less resources, as for every test run we do not start a new vm, and progress output should coming.

### CODE REVIEW

**Comment by lpil** [comment]
So `mix test` requires the mix env to be set to run.

```
louis ~/projects/mix-test.watch [(718facd...)] $ mix test.watch &
[1] 10280
louis ~/projects/mix-test.watch [(718facd...)] $ touch lib/mix_test_watch.ex

[1]+  Stopped                 mix test.watch
louis ~/projects/mix-test.watch [(718facd...)] $ fg
mix test.watch
Running tests...
** (EXIT from #PID<0.48.0>) an exception was raised:
    ** (Mix.Error) mix test is running on environment dev. If you are running tests along another task, please set MIX_ENV explicitly
        (mix) lib/mix.ex:245: Mix.raise/1
        (mix) lib/mix/tasks/test.ex:142: Mix.Tasks.Test.run/1
        lib/mix_test_watch.ex:52: Mix.Tasks.Test.Watch.run_tests/1
        lib/mix_test_watch.ex:27: Mix.Tasks.Test.Watch.handle_info/2
        (stdlib) gen_server.erl:593: :gen_server.try_dispatch/4
        (stdlib) gen_server.erl:659: :gen_server.handle_msg/5
        (stdlib) proc_lib.erl:237: :proc_lib.init_p_do_apply/3
louis ~/projects/mix-test.watch [(718facd...)] $
```

We can set it explicitly with the code as it is here, but it would be nice to avoid that.

```
louis ~/projects/mix-test.watch [(718facd...)] $ MIX_ENV=test mix test.watch &
[1] 10443
louis ~/projects/mix-test.watch [(718facd...)] $ ==> meck (compile)
Compiled lib/mix_test_watch.ex
Generated mix_test_watch.app
touch lib/mix_test_watch.ex

[1]+  Stopped                 MIX_ENV=test mix test.watch
louis ~/projects/mix-test.watch [(718facd...)] $ fg
MIX_ENV=test mix test.watch
Running tests...
test/mix_test_watch_test.exs:6: warning: unused alias Watch
.

Finished in 0.03 seconds (0.03s on load, 0.00s on tests)
1 tests, 0 failures

Randomized with seed 246717
^C
BREAK: (a)bort (c)ontinue (p)roc info (i)nfo (l)oaded
       (v)ersion (k)ill (D)b-tables (d)istribution
^Clouis ~/projects/mix-test.watch [(718facd...)] $
```

### With setting of `MIX_ENV`

We can set the env var using `System.put_env/2`, but this results in the test only dependancies never being loaded.

```
louis ~/projects/mix-test.watch [(718facd...) *] $ mix test.watch &
[1] 10624
louis ~/projects/mix-test.watch [(718facd...) *] $ Compiled lib/mix_test_watch.ex
Generated mix_test_watch.app
touch lib/mix_test_watch.ex

[1]+  Stopped                 mix test.watch
louis ~/projects/mix-test.watch [(718facd...) *] $ fg
mix test.watch
Running tests...

=ERROR REPORT==== 28-Apr-2015::13:15:37 ===
** Generic server 'Elixir.Mix.Tasks.Test.Watch' terminating
** Last message in was {<0.106.0>,
                        {fs,file_event},
                        {"/Users/louis/projects/mix-test.watch/lib/mix_test_watch.ex",
                         [created,inodemetamod,renamed,modified,changeowner,
                          xattrmod]}}
** When Server state == []
** Reason for termination ==
** {#{'__exception__' => true,
      '__struct__' => 'Elixir.CompileError',
      description => <<"module ShouldI is not loaded and could not be found">>,
      file => <<"/Users/louis/projects/mix-test.watch/test/mix_test_watch_test.exs">>,
      line => 3},
    [{'Elixir.Kernel',use,1,[{file,"expanding macro"}]},
     {'Elixir.Mix.Tasks.Test.WatchTest','__MODULE__',0,
         [{file,"test/mix_test_watch_test.exs"},{line,3}]},
     {elixir,erl_eval,3,[{file,"src/elixir.erl"},{line,194}]},
     {elixir,eval_forms,4,[{file,"src/elixir.erl"},{line,182}]},
     {elixir_compiler,eval_compilation,3,
         [{file,"src/elixir_compiler.erl"},{line,66}]},
     {elixir_lexical,run,3,[{file,"src/elixir_lexical.erl"},{line,16}]},
     {elixir_compiler,quoted,3,[{file,"src/elixir_compiler.erl"},{line,30}]},
     {'Elixir.Code',require_file,2,[{file,"lib/code.ex"},{line,316}]}]}
** (EXIT from #PID<0.48.0>) an exception was raised:
    ** (CompileError) test/mix_test_watch_test.exs:3: module ShouldI is not loaded and could not be found
        (elixir) expanding macro: Kernel.use/1
        test/mix_test_watch_test.exs:3: Mix.Tasks.Test.WatchTest (module)
        (elixir) src/elixir.erl:194: :elixir.erl_eval/3
        (elixir) src/elixir.erl:182: :elixir.eval_forms/4
        (elixir) src/elixir_compiler.erl:66: :elixir_compiler.eval_compilation/3
        (elixir) src/elixir_lexical.erl:16: :elixir_lexical.run/3
        (elixir) src/elixir_compiler.erl:30: :elixir_compiler.quoted/3
        (elixir) lib/code.ex:316: Code.require_file/2
louis ~/projects/mix-test.watch [(718facd...) *] $
```

Do you have a solution to this problem? Currently I'm leaning towards a ports based solution as this is getting rather fiddly.

**Comment by liveforeverx** [comment]
"Do you have a solution to this problem?"

Yes, last commit fix the problem. The problem was, that Mix.CLI on start checks the environment and magically set it to test for test(I've added to a start, that we simply make the same magic). 

And, the next, we need to load right pathes with right enviroment, thats why I reenable the tasks, always to load correct pathes.

**Comment by casio** [comment]
Has there been progress on this? Or maybe a different workaround to more prompty iterating on file changes / tests?

**Comment by liveforeverx** [comment]
@casio : my branch worked some time ago, but I haven't maintained it further, so because @lpil decided definitely do not merge it to master, just FYI.

**Comment by lpil** [comment]
As I was unable to merge this branch after code changes I've been using it as the basis for a new branch that does the same (and learnt a lot about the compiler in the process!).

It's not entirely ready yet though. I'm having some difficulties with warnings that are detailed in the other pull request.

**Pull request closed without merging**
